### ISSUE TITLE
Add Timezone Feature

### ISSUE THREAD

**Issue by Lycol50** [killer549/RealTime#2]
Can you add timezone feature, so that it does not rely on UTC Timezone and we can change it anytime on config.yml

Thanks

**Comment by patahgaming** [comment]
edit your php.ini your in vps? setting bin\php7\bin\php.ini time zone date

**Comment by ahmedhozny** [comment]
Imma add this information to readme and plugin page on poggit.

And yeah it's my fault I should have added that earlier.
